#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generate pixel-pd-lists.h: the save lists of the domains pixel-pd-off can
power back on.

Input: Google's drivers/soc/google/cal-if/gs201/flexpmu_cal_local_gs201.h
(GPL-2.0-only, Copyright (c) 2021 Samsung Electronics Co., Ltd.), the same
file kernel/suspend/gen-sleep-lists.py reads. For each domain in DOMAINS it
emits the SAVE_RESTORE entries of `<domain>_save[]` in order, as physical
addresses, each tagged with its line. Stock saves them before the domain's
`_off` sequence and writes them back after `_on` (pmucal_local.c:63,119).
The lists' debug READs (DBG_NFO_*) are left out; any other access type is
refused, so a PLL wait can never be replayed as a register write.

Usage: gen-pd-lists.py LOCAL_H [-o pixel-pd-lists.h]
"""
import argparse
import re
import sys

DOMAINS = ("csis", "pdp")
# Register blocks the lists may touch: the domain's own CMU and SYSREG.
BLOCKS = {
    "csis": (0x1A400000, 0x1A420000),
    "pdp": (0x1AA00000, 0x1AA20000),
}
SEQ = re.compile(r'PMUCAL_SEQ_DESC\((\w+), "(\w+)", (0x[0-9a-f]+), (0x[0-9a-f]+),')


def lists(path):
    found = {}
    current = None
    with open(path) as f:
        for number, line in enumerate(f, 1):
            start = re.match(r"struct pmucal_seq (\w+)_save\[\] = \{", line)
            if start:
                current = start.group(1) if start.group(1) in DOMAINS else None
                if current:
                    found[current] = []
                continue
            if current and line.startswith("};"):
                current = None
                continue
            if not current:
                continue
            m = SEQ.search(line)
            if not m:
                continue
            kind, name, base, offset = m.group(1), m.group(2), int(m.group(3), 16), int(m.group(4), 16)
            if kind == "PMUCAL_READ":
                continue
            if kind != "PMUCAL_SAVE_RESTORE":
                sys.exit(f"{current}_save line {number}: {kind} {name} is not a plain save/restore")
            if base not in BLOCKS[current]:
                sys.exit(f"{current}_save line {number}: {name} at {base:#x} is outside the domain")
            found[current].append((base + offset, name, number))
    missing = [d for d in DOMAINS if d not in found]
    if missing:
        sys.exit(f"no save list for {', '.join(missing)}")
    return found


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("local_h")
    ap.add_argument("-o", "--output", default="pixel-pd-lists.h")
    a = ap.parse_args()
    found = lists(a.local_h)
    out = ["/* SPDX-License-Identifier: GPL-2.0-only */",
           "/* Generated by gen-pd-lists.py from Google's flexpmu_cal_local_gs201.h",
           " * (Copyright (c) 2021 Samsung Electronics Co., Ltd.). Do not edit. */",
           "#ifndef PIXEL_PD_LISTS_H", "#define PIXEL_PD_LISTS_H", ""]
    for domain in DOMAINS:
        out.append(f"static const struct pd_reg {domain}_save[] = {{")
        for pa, name, number in found[domain]:
            out.append(f"\t{{ {pa:#010x}, \"{name}\" }},\t/* line {number} */")
        out += ["};", ""]
    out.append("#endif")
    with open(a.output, "w") as f:
        f.write("\n".join(out) + "\n")
    print(", ".join(f"{d} {len(found[d])}" for d in DOMAINS))


if __name__ == "__main__":
    main()
