/* SPDX-License-Identifier: GPL-2.0-only */
/* Generated by gen-pd-lists.py from Google's flexpmu_cal_local_gs201.h
 * (Copyright (c) 2021 Samsung Electronics Co., Ltd.). Do not edit. */
#ifndef PIXEL_PD_LISTS_H
#define PIXEL_PD_LISTS_H

static const struct pd_reg csis_save[] = {
	{ 0x1a401800, "CLK_CON_DIV_DIV_CLK_CSIS_NOCP" },	/* line 912 */
	{ 0x1a400600, "PLL_CON0_MUX_CLKCMU_CSIS_NOC_USER" },	/* line 913 */
	{ 0x1a403050, "QCH_CON_CSISX8_QCH_C2_CSIS" },	/* line 914 */
	{ 0x1a403054, "QCH_CON_CSISX8_QCH_CSIS_DMA" },	/* line 915 */
	{ 0x1a403058, "QCH_CON_CSISX8_QCH_EBUF" },	/* line 916 */
	{ 0x1a40305c, "QCH_CON_CSIS_CMU_CSIS_QCH" },	/* line 917 */
	{ 0x1a403060, "QCH_CON_D_TZPC_CSIS_QCH" },	/* line 918 */
	{ 0x1a403064, "QCH_CON_GPC_CSIS_QCH" },	/* line 919 */
	{ 0x1a403068, "QCH_CON_LH_AST_MI_L_OTF0_PDP_CSIS_QCH" },	/* line 920 */
	{ 0x1a40306c, "QCH_CON_LH_AST_MI_L_OTF1_PDP_CSIS_QCH" },	/* line 921 */
	{ 0x1a403070, "QCH_CON_LH_AST_MI_L_OTF2_PDP_CSIS_QCH" },	/* line 922 */
	{ 0x1a403074, "QCH_CON_LH_AST_MI_L_SOTF0_IPP_CSIS_QCH" },	/* line 923 */
	{ 0x1a403078, "QCH_CON_LH_AST_MI_L_SOTF1_IPP_CSIS_QCH" },	/* line 924 */
	{ 0x1a40307c, "QCH_CON_LH_AST_MI_L_SOTF2_IPP_CSIS_QCH" },	/* line 925 */
	{ 0x1a403080, "QCH_CON_LH_AST_MI_L_VO_MCSC_CSIS_QCH" },	/* line 926 */
	{ 0x1a403084, "QCH_CON_LH_AST_MI_L_ZOTF0_IPP_CSIS_QCH" },	/* line 927 */
	{ 0x1a403088, "QCH_CON_LH_AST_MI_L_ZOTF1_IPP_CSIS_QCH" },	/* line 928 */
	{ 0x1a40308c, "QCH_CON_LH_AST_MI_L_ZOTF2_IPP_CSIS_QCH" },	/* line 929 */
	{ 0x1a403090, "QCH_CON_LH_AST_SI_L_OTF0_CSIS_PDP_QCH" },	/* line 930 */
	{ 0x1a403094, "QCH_CON_LH_AST_SI_L_OTF1_CSIS_PDP_QCH" },	/* line 931 */
	{ 0x1a403098, "QCH_CON_LH_AST_SI_L_OTF2_CSIS_PDP_QCH" },	/* line 932 */
	{ 0x1a40309c, "QCH_CON_LH_AST_SI_L_VO_CSIS_PDP_QCH" },	/* line 933 */
	{ 0x1a4030a0, "QCH_CON_LH_AXI_MI_LD_PDP_CSIS_QCH" },	/* line 934 */
	{ 0x1a4030a4, "QCH_CON_LH_AXI_SI_D0_CSIS_QCH" },	/* line 935 */
	{ 0x1a4030a8, "QCH_CON_LH_AXI_SI_D1_CSIS_QCH" },	/* line 936 */
	{ 0x1a4030b0, "QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS0" },	/* line 937 */
	{ 0x1a4030b4, "QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS1" },	/* line 938 */
	{ 0x1a4030b8, "QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS2" },	/* line 939 */
	{ 0x1a4030bc, "QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS3" },	/* line 940 */
	{ 0x1a4030c0, "QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS4" },	/* line 941 */
	{ 0x1a4030c4, "QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS5" },	/* line 942 */
	{ 0x1a4030c8, "QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS6" },	/* line 943 */
	{ 0x1a4030cc, "QCH_CON_MIPI_PHY_LINK_WRAP_QCH_CSIS7" },	/* line 944 */
	{ 0x1a4030d0, "QCH_CON_PPMU_D0_QCH" },	/* line 945 */
	{ 0x1a4030d4, "QCH_CON_PPMU_D1_QCH" },	/* line 946 */
	{ 0x1a4030d8, "QCH_CON_QE_CSIS_DMA0_QCH" },	/* line 947 */
	{ 0x1a4030dc, "QCH_CON_QE_CSIS_DMA1_QCH" },	/* line 948 */
	{ 0x1a4030e0, "QCH_CON_QE_CSIS_DMA2_QCH" },	/* line 949 */
	{ 0x1a4030e4, "QCH_CON_QE_CSIS_DMA3_QCH" },	/* line 950 */
	{ 0x1a4030e8, "QCH_CON_QE_STRP0_QCH" },	/* line 951 */
	{ 0x1a4030ec, "QCH_CON_QE_STRP1_QCH" },	/* line 952 */
	{ 0x1a4030f0, "QCH_CON_QE_STRP2_QCH" },	/* line 953 */
	{ 0x1a4030f4, "QCH_CON_QE_ZSL0_QCH" },	/* line 954 */
	{ 0x1a4030f8, "QCH_CON_QE_ZSL1_QCH" },	/* line 955 */
	{ 0x1a4030fc, "QCH_CON_QE_ZSL2_QCH" },	/* line 956 */
	{ 0x1a403100, "QCH_CON_SLH_AXI_MI_P_CSIS_QCH" },	/* line 957 */
	{ 0x1a403108, "QCH_CON_SSMT_D0_QCH" },	/* line 958 */
	{ 0x1a40310c, "QCH_CON_SSMT_D1_QCH" },	/* line 959 */
	{ 0x1a403110, "QCH_CON_SYSMMU_D0_CSIS_QCH_S1" },	/* line 960 */
	{ 0x1a403114, "QCH_CON_SYSMMU_D0_CSIS_QCH_S2" },	/* line 961 */
	{ 0x1a403118, "QCH_CON_SYSMMU_D1_CSIS_QCH_S1" },	/* line 962 */
	{ 0x1a40311c, "QCH_CON_SYSMMU_D1_CSIS_QCH_S2" },	/* line 963 */
	{ 0x1a403120, "QCH_CON_SYSREG_CSIS_QCH" },	/* line 964 */
	{ 0x1a400800, "CSIS_CMU_CSIS_CONTROLLER_OPTION" },	/* line 965 */
	{ 0x1a420104, "BUS_COMPONENT_DRCG_EN" },	/* line 966 */
	{ 0x1a420108, "MEMCLK" },	/* line 967 */
};

static const struct pd_reg pdp_save[] = {
	{ 0x1aa01800, "CLK_CON_DIV_DIV_CLK_PDP_NOCP" },	/* line 1037 */
	{ 0x1aa00600, "PLL_CON0_MUX_CLKCMU_PDP_NOC_USER" },	/* line 1038 */
	{ 0x1aa00610, "PLL_CON0_MUX_CLKCMU_PDP_VRA_USER" },	/* line 1039 */
	{ 0x1aa03050, "QCH_CON_D_TZPC_PDP_QCH" },	/* line 1040 */
	{ 0x1aa03054, "QCH_CON_GPC_PDP_QCH" },	/* line 1041 */
	{ 0x1aa03058, "QCH_CON_LH_AST_MI_L_OTF0_CSIS_PDP_QCH" },	/* line 1042 */
	{ 0x1aa0305c, "QCH_CON_LH_AST_MI_L_OTF1_CSIS_PDP_QCH" },	/* line 1043 */
	{ 0x1aa03060, "QCH_CON_LH_AST_MI_L_OTF2_CSIS_PDP_QCH" },	/* line 1044 */
	{ 0x1aa03064, "QCH_CON_LH_AST_MI_L_VO_CSIS_PDP_QCH" },	/* line 1045 */
	{ 0x1aa03068, "QCH_CON_LH_AST_SI_L_OTF0_PDP_CSIS_QCH" },	/* line 1046 */
	{ 0x1aa0306c, "QCH_CON_LH_AST_SI_L_OTF0_PDP_G3AA_QCH" },	/* line 1047 */
	{ 0x1aa03070, "QCH_CON_LH_AST_SI_L_OTF0_PDP_IPP_QCH" },	/* line 1048 */
	{ 0x1aa03074, "QCH_CON_LH_AST_SI_L_OTF1_PDP_CSIS_QCH" },	/* line 1049 */
	{ 0x1aa03078, "QCH_CON_LH_AST_SI_L_OTF1_PDP_G3AA_QCH" },	/* line 1050 */
	{ 0x1aa0307c, "QCH_CON_LH_AST_SI_L_OTF1_PDP_IPP_QCH" },	/* line 1051 */
	{ 0x1aa03080, "QCH_CON_LH_AST_SI_L_OTF2_PDP_CSIS_QCH" },	/* line 1052 */
	{ 0x1aa03084, "QCH_CON_LH_AST_SI_L_OTF2_PDP_G3AA_QCH" },	/* line 1053 */
	{ 0x1aa03088, "QCH_CON_LH_AST_SI_L_OTF2_PDP_IPP_QCH" },	/* line 1054 */
	{ 0x1aa0308c, "QCH_CON_LH_AST_SI_L_VO_PDP_IPP_QCH" },	/* line 1055 */
	{ 0x1aa03090, "QCH_CON_LH_AST_SI_L_YOTF0_PDP_G3AA_QCH" },	/* line 1056 */
	{ 0x1aa03094, "QCH_CON_LH_AST_SI_L_YOTF1_PDP_G3AA_QCH" },	/* line 1057 */
	{ 0x1aa03098, "QCH_CON_LH_AXI_SI_LD_PDP_CSIS_QCH" },	/* line 1058 */
	{ 0x1aa0309c, "QCH_CON_LH_AXI_SI_LD_PDP_DNS_QCH" },	/* line 1059 */
	{ 0x1aa030a4, "QCH_CON_PDP_CMU_PDP_QCH" },	/* line 1060 */
	{ 0x1aa030a8, "QCH_CON_PDP_TOP_QCH_C2_PDP" },	/* line 1061 */
	{ 0x1aa030ac, "QCH_CON_PDP_TOP_QCH_PDP_TOP" },	/* line 1062 */
	{ 0x1aa030b0, "QCH_CON_PPMU_VRA_QCH" },	/* line 1063 */
	{ 0x1aa030b4, "QCH_CON_QE_PDP_AF0_QCH" },	/* line 1064 */
	{ 0x1aa030b8, "QCH_CON_QE_PDP_AF1_QCH" },	/* line 1065 */
	{ 0x1aa030bc, "QCH_CON_QE_PDP_STAT0_QCH" },	/* line 1066 */
	{ 0x1aa030c0, "QCH_CON_QE_PDP_STAT1_QCH" },	/* line 1067 */
	{ 0x1aa030c4, "QCH_CON_QE_VRA_QCH" },	/* line 1068 */
	{ 0x1aa030c8, "QCH_CON_SLH_AXI_MI_P_PDP_QCH" },	/* line 1069 */
	{ 0x1aa030cc, "QCH_CON_SSMT_PDP_STAT_QCH" },	/* line 1070 */
	{ 0x1aa030d0, "QCH_CON_SSMT_VRA_QCH" },	/* line 1071 */
	{ 0x1aa030d4, "QCH_CON_SYSREG_PDP_QCH" },	/* line 1072 */
	{ 0x1aa030d8, "QCH_CON_VRA_QCH" },	/* line 1073 */
	{ 0x1aa00800, "PDP_CMU_PDP_CONTROLLER_OPTION" },	/* line 1074 */
	{ 0x1aa20104, "BUS_COMPONENT_DRCG_EN" },	/* line 1075 */
	{ 0x1aa20108, "MEMCLK" },	/* line 1076 */
};

#endif
